NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.school.id.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.school.id.com-cert.pem
    OrganizationalUnitIdentifier: peer
